-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM (SELECT * FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE "%Intact%") I
INNER JOIN (SELECT * FROM ANIMAL_OUTS WHERE NOT SEX_UPON_OUTCOME LIKE "%Intact%") O
ON I.ANIMAL_ID = O.ANIMAL_ID;