-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS "TOTAL PRICE"
FROM FOOD_PRODUCT P
INNER JOIN (SELECT * FROM FOOD_ORDER WHERE PRODUCE_DATE LIKE "2022-05%") O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_ID
ORDER BY SUM(P.PRICE * O.AMOUNT) DESC, PRODUCT_ID;